### PR TITLE
read ELF .text section header for address and size and create LD_PRELOAD target

### PR DESCRIPTION
**Pull request by gabrielschulhof**
This change removes the need for a special symbol in the target binary. Instead, it reads the binary's ELF section headers to determine the address and size of the `.text` section. This, in turn, allows us to create a LD_PRELOAD library that can be used with any object in any process to attempt to re-map its `.text` section.

### CODE REVIEW

**Comment by grahamwhaley** [comment]
/me will try this out in the morning - thanks!

**Comment by grahamwhaley** [comment]
Hmm, I thought we must have merged this by now....
this **LGTM** - seems to work really well, and is much better than having to modify the target app and having to shuffle around to not remap the loader/remapper.... v.nice.
/cc @uttampawar @suresh-srinivas

**Comment by grahamwhaley** [comment]
and then having said that.... I was messing about and just ran:

```bash
$ LD_PRELOAD=/home/gwhaley/go/src/github.com/intel/iodlr/large_page-c/liblppreload.so perf stat -d -d -d openssl speed bf
Mapping to large pages failed: map region too small
Aborted (core dumped)
```

Hmm, I wonder if dying due to failure to map as the text section is too small should be fatal. Maybe a warning message in this case is more meaningful?
(and, yes, I know the above probably tried to map `perf` and not `openssl` ;-) )

**Comment by gabrielschulhof** [comment]
@grahamwhaley I left the abort in because reading the stderr can be hard with a systemd service. Unfortunately, aborting will not cause systemd to output the stderr either. Yet we don't really want users to think the code has been remapped, whereas it hasn't really, because then they'll think the tool is useless.

We have to figure out how to sneak a conspicuous enough indication of failure past systemd and/or any other wrappers that may surround the given process.

I guess documentation is a partial solution, and that's also missing.

**Comment by gabrielschulhof** [comment]
@grahamwhaley I added documentation to `README.md` and I removed the `abort()`. PTAL!

**Comment by gabrielschulhof** [comment]
@suresh-srinivas that's a good point. I was thinking about moving the code that reads the ELF into lp_preload.c.

**Comment by suresh-srinivas** [comment]
> Let's not merge the code yet. I'm reviewing it.

This is blocking Integration work. Can we review soon and merge it? Or merge it and fix additional things we find in subsequent PR's.

**Comment by uttampawar** [comment]
Code can be improved but overall it looks okay.

**Pull request merged**
